"""Governed MMM fixture dashboard/report demo artifacts."""

from __future__ import annotations

import re
from collections.abc import Mapping
from dataclasses import dataclass

from mip.adapters.governance import (
    adapter_output_id,
    adapter_output_to_decision_surface,
    trust_report_for_adapter_output,
)
from mip.adapters.mmm import (
    build_mmm_adapter_input,
    build_mmm_adapter_output_placeholder,
)
from mip.contracts import DecisionSurface, TrustReport
from mip.workflows.configs.mmm import MMMConfigDraft
from mip.workflows.intake.requirements import WorkflowType
from mip.workflows.orchestrator import WorkflowRunSummary

_PLACEHOLDER_LABELS = (
    "adapter_fixture_placeholder_only",
    "diagnostic_only",
    "not_model_execution",
    "not_decision_ready",
)

_MISSING_PRODUCTION_REQUIREMENTS = (
    "Real MMM engine adapter connected",
    "Full-panel Δμ decision surface generated by engine",
    "Reliability scorecard attached",
    "Calibration evidence audited",
    "TrustReport passes production gates",
    "Human approval before budget action",
)

_FORBIDDEN_CLAIM_PHRASES = (
    "actual roi",
    "true roi",
    "incremental lift",
    "causal impact",
    "model result",
    "budget recommendation",
)

_DISCLAIMER = (
    "MMM fixture governance demo only. This surface is an adapter placeholder, "
    "not model execution. Diagnostic only and not decision-ready."
)


@dataclass(frozen=True)
class MMMFixtureReport:
    """Governed MMM fixture report bundle for dashboard/report rendering."""

    objective_type: str
    config_draft_status: str
    production_eligible: bool
    adapter_input_status: str
    adapter_output_status: str
    source_config_marker: str
    adapter_output_id: str
    decision_surface_id: str
    decision_surface_type: str
    decision_surface_certification_status: str
    trust_report_confidence_tier: str
    trust_report_warnings: list[str]
    trust_report_unsupported_claims: list[str]
    trust_report_assumptions: list[str]
    placeholder_labels: list[str]
    missing_production_requirements: list[str]
    placeholder_explanation: str
    disclaimer: str


_MMM_WORKFLOW_TYPES = frozenset(
    {
        WorkflowType.MMM_CHANNEL_ROI,
        WorkflowType.MMM_BUDGET_ALLOCATION,
        WorkflowType.SCENARIO_PLANNING,
    }
)


def build_mmm_fixture_report(summary: WorkflowRunSummary) -> MMMFixtureReport | None:
    """Build a governed MMM fixture report when the workflow has an MMM config draft."""
    if not isinstance(summary.config_draft, MMMConfigDraft):
        return None

    workflow_type = summary.config_draft.metadata.workflow_type
    if workflow_type not in _MMM_WORKFLOW_TYPES:
        return None

    if _enum_value(summary.config_draft.metadata.status) == "blocked":
        return None

    try:
        adapter_input = build_mmm_adapter_input(summary.config_draft)
    except ValueError:
        return None

    adapter_output = build_mmm_adapter_output_placeholder(summary.config_draft)
    surface = adapter_output_to_decision_surface(adapter_output)
    trust_report = trust_report_for_adapter_output(adapter_output)

    report = MMMFixtureReport(
        objective_type=_enum_value(summary.objective.objective_type),
        config_draft_status=_enum_value(summary.config_draft.metadata.status),
        production_eligible=summary.config_draft.metadata.production_eligible,
        adapter_input_status=_enum_value(adapter_input.status),
        adapter_output_status=_enum_value(adapter_output.status),
        source_config_marker=summary.config_draft.metadata.generated_marker,
        adapter_output_id=adapter_output_id(adapter_output),
        decision_surface_id=surface.surface_id,
        decision_surface_type=_enum_value(surface.surface_type),
        decision_surface_certification_status=_enum_value(surface.certification_status),
        trust_report_confidence_tier=_enum_value(trust_report.confidence_tier),
        trust_report_warnings=list(trust_report.warnings),
        trust_report_unsupported_claims=list(trust_report.unsupported_claims),
        trust_report_assumptions=list(trust_report.assumptions),
        placeholder_labels=list(_PLACEHOLDER_LABELS),
        missing_production_requirements=list(_MISSING_PRODUCTION_REQUIREMENTS),
        placeholder_explanation=_placeholder_explanation(surface, trust_report),
        disclaimer=format_mmm_fixture_disclaimer(),
    )
    assert_safe_mmm_fixture_report(report)
    return report


def mmm_fixture_report_sections(report: MMMFixtureReport) -> dict[str, str | list[str] | bool]:
    """Render an MMM fixture report as UI/report sections."""
    sections: dict[str, str | list[str] | bool] = {
        "objective_type": report.objective_type,
        "config_draft_status": report.config_draft_status,
        "production_eligible": report.production_eligible,
        "adapter_input_status": report.adapter_input_status,
        "adapter_output_status": report.adapter_output_status,
        "source_config_marker": report.source_config_marker,
        "adapter_output_id": report.adapter_output_id,
        "decision_surface_id": report.decision_surface_id,
        "decision_surface_type": report.decision_surface_type,
        "decision_surface_certification_status": report.decision_surface_certification_status,
        "trust_report_confidence_tier": report.trust_report_confidence_tier,
        "trust_report_warnings": report.trust_report_warnings,
        "trust_report_unsupported_claims": report.trust_report_unsupported_claims,
        "trust_report_assumptions": report.trust_report_assumptions,
        "placeholder_labels": report.placeholder_labels,
        "missing_production_requirements": report.missing_production_requirements,
        "placeholder_explanation": report.placeholder_explanation,
        "disclaimer": report.disclaimer,
        "placeholder_banner": (
            "adapter_fixture_placeholder_only | diagnostic_only | "
            "not_model_execution | not_decision_ready"
        ),
    }
    assert_safe_mmm_fixture_report(sections)
    return sections


def format_mmm_fixture_disclaimer() -> str:
    """Return the standard MMM fixture demo disclaimer."""
    return _DISCLAIMER


def assert_safe_mmm_fixture_report(
    report_or_sections: MMMFixtureReport | Mapping[str, object],
) -> None:
    """Raise if report content includes forbidden causal/model-output claims."""
    combined = _collect_report_text(report_or_sections).lower()
    for phrase in _FORBIDDEN_CLAIM_PHRASES:
        if phrase in combined:
            msg = f"mmm fixture report must not include forbidden phrase: {phrase}"
            raise ValueError(msg)
    if _contains_false_production_ready_claim(combined):
        msg = "mmm fixture report must not claim production-ready status"
        raise ValueError(msg)


def _placeholder_explanation(surface: DecisionSurface, trust_report: TrustReport) -> str:
    return (
        "This DecisionSurface is an adapter fixture placeholder only. "
        f"Surface type is {_enum_value(surface.surface_type)} with certification status "
        f"{_enum_value(surface.certification_status)}. TrustReport confidence tier is "
        f"{_enum_value(trust_report.confidence_tier)}. No MMM engine execution occurred."
    )


def _collect_report_text(report_or_sections: MMMFixtureReport | Mapping[str, object]) -> str:
    if isinstance(report_or_sections, MMMFixtureReport):
        payload: dict[str, object] = {
            "objective_type": report_or_sections.objective_type,
            "config_draft_status": report_or_sections.config_draft_status,
            "production_eligible": report_or_sections.production_eligible,
            "adapter_input_status": report_or_sections.adapter_input_status,
            "adapter_output_status": report_or_sections.adapter_output_status,
            "source_config_marker": report_or_sections.source_config_marker,
            "adapter_output_id": report_or_sections.adapter_output_id,
            "decision_surface_id": report_or_sections.decision_surface_id,
            "decision_surface_type": report_or_sections.decision_surface_type,
            "decision_surface_certification_status": (
                report_or_sections.decision_surface_certification_status
            ),
            "trust_report_confidence_tier": report_or_sections.trust_report_confidence_tier,
            "trust_report_warnings": report_or_sections.trust_report_warnings,
            "trust_report_unsupported_claims": report_or_sections.trust_report_unsupported_claims,
            "trust_report_assumptions": report_or_sections.trust_report_assumptions,
            "placeholder_labels": report_or_sections.placeholder_labels,
            "missing_production_requirements": report_or_sections.missing_production_requirements,
            "placeholder_explanation": report_or_sections.placeholder_explanation,
            "disclaimer": report_or_sections.disclaimer,
        }
    else:
        payload = dict(report_or_sections)
    return _collect_strings(payload)


def _collect_strings(value: object) -> str:
    if isinstance(value, str):
        return value
    if isinstance(value, bool):
        return str(value)
    if isinstance(value, dict):
        return "\n".join(_collect_strings(item) for item in value.values())
    if isinstance(value, list):
        return "\n".join(_collect_strings(item) for item in value)
    return ""


def _contains_false_production_ready_claim(text: str) -> bool:
    for match in re.finditer(r"production[- ]ready", text):
        start = match.start()
        prefix = text[max(0, start - 4) : start]
        if not prefix.endswith("not "):
            return True
    return False


def _enum_value(value: object) -> str:
    if isinstance(value, str):
        return value
    return str(getattr(value, "value", value))
